version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bibliodex
      POSTGRES_PASSWORD: bibliodex
      POSTGRES_DB: bibliodex_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bibliodex:bibliodex@db:5432/bibliodex_db
    volumes:
      - ./backend:/code

volumes:
  db_data:

